import 'dotenv/config';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { eq, inArray } from 'drizzle-orm';

if (process.env.RUN_SMOKE !== '1') throw new Error('Explicitly set RUN_SMOKE=1. Run only against a disposable local preview.');
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { db, pool } = await import('../src/db/index.ts');
const { admins, orders, plans, paymentSettings } = await import('../src/db/schema.ts');
const existing = await db.select().from(admins);
if (existing.length) { await pool.end(); throw new Error('Refusing to run initialization tests against an existing administrator.'); }
const base = process.env.SMOKE_URL || 'http://localhost:3000';
const suffix = randomBytes(5).toString('hex');
const username = `smoke_${suffix}`;
const password = randomBytes(16).toString('hex');
const email = `smoke-${suffix}@example.com`;
const fixtureIds = [];
let fixturePlanId;
const [originalSettings] = await db.select().from(paymentSettings);
assert.ok(!originalSettings?.usdtEnabled && !originalSettings?.alipayEnabled, 'Payment channels must be disabled for non-financial smoke tests.');
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
page.setDefaultTimeout(15000);
const browserErrors = [];
page.on('pageerror', error => browserErrors.push(error.message));
const call = async (path, method = 'GET', data) => {
  const response = await context.request.fetch(`${base}${path}`, { method, ...(data ? { data } : {}) });
  return { status: response.status(), data: await response.json().catch(() => null) };
};
const log = message => console.log(`PASS: ${message}`);
try {
  assert.equal((await call('/api/admin/orders')).status, 401);
  assert.equal((await call('/api/orders', 'POST', { planId: 'chatgpt-monthly', email: 'bad', accepted: true, paymentMethod: 'usdt' })).status, 400);
  log('Protected admin API and order input validation');
  await page.goto(base, { waitUntil: 'networkidle' });
  assert.equal(await page.locator('.plan-card').count(), 4);
  await page.getByRole('button', { name: 'Claude', exact: true }).click();
  assert.equal(await page.locator('.plan-card').count(), 1);
  await page.getByRole('button', { name: /按年订阅/ }).click();
  assert.match(await page.locator('.plan-price').innerText(), /1,499/);
  await page.getByRole('button', { name: /^全部套餐/ }).click();
  await page.getByRole('button', { name: '按月订阅', exact: true }).click();
  assert.equal(await page.locator('.plan-card').count(), 4);
  await page.getByRole('button', { name: '支持哪些支付方式？', exact: true }).click();
  assert.equal(await page.locator('.faq-item.open').count(), 1);
  await page.getByRole('button', { name: '打开订单帮助' }).click();
  await page.getByRole('heading', { name: '让充值更简单一点。' }).waitFor();
  await page.getByRole('button', { name: '关闭帮助' }).click();
  log('Brand filters, annual pricing, FAQ accordion and help dialog');
  await page.getByRole('link', { name: '立即充值', exact: true }).first().click();
  await page.getByLabel('账号邮箱', { exact: false }).first().fill(email);
  await page.getByLabel('再次确认邮箱', { exact: false }).fill('different@example.com');
  await page.locator('input[type=checkbox]').check();
  await page.getByRole('button', { name: '继续，选择支付方式' }).click();
  await page.getByRole('alert').filter({ hasText: '两次填写的账号邮箱不一致' }).waitFor();
  await page.getByLabel('再次确认邮箱', { exact: false }).fill(email);
  await page.screenshot({ path: 'artifacts/checkout-desktop.png', fullPage: true });
  await page.getByRole('button', { name: '继续，选择支付方式' }).click();
  await page.getByRole('radio', { name: /USDT/ }).click();
  const createdResponse = page.waitForResponse(response => response.url().endsWith('/api/orders') && response.request().method() === 'POST');
  await page.getByRole('button', { name: '创建订单并前往支付' }).click();
  const created = await (await createdResponse).json();
  assert.ok(created.id); fixtureIds.push(created.id);
  await page.waitForURL(`**/orders/${created.id}/payment`);
  await page.getByRole('heading', { name: '收款通道准备中' }).waitFor();
  await page.screenshot({ path: 'artifacts/payment-desktop.png', fullPage: true });
  const publicOrder = (await call(`/api/orders/${created.id}`)).data;
  assert.equal(publicOrder.status, 'pending'); assert.equal(publicOrder.amount, '119.00'); assert.notEqual(publicOrder.email, email);
  log('Two-step checkout, frozen server price, private account masking and disabled gateway safety');
  await page.goto(`${base}/orders`);
  await page.locator('input[name=orderCode]').fill(created.code);
  await page.getByLabel('账号邮箱').fill('wrong@example.com');
  await page.getByRole('button', { name: '查询订单', exact: true }).click();
  await page.getByRole('alert').waitFor();
  await page.getByLabel('账号邮箱').fill(email);
  await page.getByRole('button', { name: '查询订单', exact: true }).click();
  await page.waitForURL(`**/orders/${created.id}/result`);
  await page.getByRole('button', { name: '取消未付款订单' }).click();
  await page.getByRole('button', { name: '我未付款，确认取消' }).click();
  await page.getByRole('heading', { name: '订单已取消，下次灵感见。' }).waitFor();
  assert.equal((await call(`/api/orders/${created.id}`)).data.status, 'cancelled');
  log('Email-verified lookup, restored order link and safe cancellation');
  const second = await call('/api/orders', 'POST', { planId: 'claude-monthly', email, paymentMethod: 'alipay', accepted: true, amount: '0.01' });
  assert.equal(second.status, 201); fixtureIds.push(second.data.id);
  assert.equal((await call(`/api/orders/${second.data.id}`)).data.amount, '139.00');
  await page.goto(`${base}/admin-login`);
  await page.screenshot({ path: 'artifacts/admin-login.png', fullPage: true });
  // 登录页不再提供初始化表单：管理员注册改在服务端，验收脚本直接调引导接口
  const setup = await call('/api/auth', 'POST', { action: 'setup', username, password, setupToken: process.env.ADMIN_SETUP_TOKEN || '' });
  assert.equal(setup.status, 200);
  await page.getByLabel('管理员账号').fill(username);
  await page.getByLabel('登录密码').fill(password);
  await page.getByRole('button', { name: '登录管理控制台' }).click();
  await page.waitForURL(`${base}/admin`);
  await page.locator('.stat-card').first().waitFor();
  assert.equal((await call('/api/admin/orders')).status, 200);
  log('Server-side admin bootstrap, secure session and protected dashboard');
  await page.goto(`${base}/admin/orders?q=${second.data.code}`);
  await page.getByRole('button', { name: '查看', exact: true }).waitFor();
  for (const status of ['paid', 'processing', 'completed']) {
    await page.getByRole('button', { name: '查看', exact: true }).click();
    const dialog = page.getByRole('dialog');
    await dialog.getByLabel('订单状态').selectOption(status);
    if (status === 'paid') await dialog.locator('input[type=checkbox]').check();
    await dialog.getByLabel('处理说明（用户可见）').fill('临时验收记录，测试结束将清理。');
    const saved = page.waitForResponse(response => response.url().includes(`/api/admin/orders/${second.data.id}`) && response.request().method() === 'PATCH');
    await dialog.getByRole('button', { name: '保存订单变更' }).click();
    assert.equal((await saved).status(), 200);
    await dialog.waitFor({ state: 'hidden' });
    await page.locator(`.data-table .status-${status}`).waitFor();
  }
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: '导出本页' }).click();
  assert.match((await download).suggestedFilename(), /haiou-orders/);
  await page.getByRole('button', { name: '已完成', exact: true }).click();
  await page.locator('.data-table .status-completed').waitFor();
  assert.equal((await call(`/api/orders/${second.data.id}`, 'PATCH', { action: 'cancel' })).status, 409);
  log('Status filters, manual confirmation, forward-only lifecycle and CSV export');
  await page.goto(`${base}/orders/${second.data.id}/result`);
  await page.getByRole('heading', { name: '能量已满格，开始创造吧。' }).waitFor();
  await page.screenshot({ path: 'artifacts/order-result.png', fullPage: true });
  await page.goto(`${base}/admin/plans`);
  await page.getByRole('button', { name: '新增套餐' }).click();
  let dialog = page.getByRole('dialog');
  const testPlanName = `验收测试 ${suffix}`;
  await dialog.getByLabel('套餐名称').fill(testPlanName);
  await dialog.getByLabel('一句话描述').fill('临时验收套餐，不公开上架');
  await dialog.getByLabel('售价（CNY）').fill('9.99');
  await dialog.getByLabel('套餐权益（每行一条）').fill('测试权益一\n测试权益二\n测试权益三');
  await dialog.locator('input[type=checkbox]').uncheck();
  const planCreated = page.waitForResponse(response => response.url().endsWith('/api/admin/plans') && response.request().method() === 'POST');
  await dialog.getByRole('button', { name: '保存套餐' }).click();
  const plan = await (await planCreated).json(); fixturePlanId = plan.id; assert.ok(plan.id); assert.equal(plan.active, false);
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.locator('.admin-plan').filter({ hasText: testPlanName }).getByRole('button', { name: '编辑套餐' }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('售价（CNY）').fill('11.12');
  const planSaved = page.waitForResponse(response => response.url().endsWith(`/api/admin/plans/${plan.id}`) && response.request().method() === 'PATCH');
  await dialog.getByRole('button', { name: '保存套餐' }).click();
  assert.equal((await (await planSaved).json()).price, '11.12');
  log('Plan creation, inactive visibility and editable package pricing');
  await page.goto(`${base}/admin/payments`);
  await page.getByLabel('兑换汇率（1 USDT = ? CNY）').fill('7.3500');
  const settingsSaved = page.waitForResponse(response => response.url().endsWith('/api/admin/settings') && response.request().method() === 'PATCH');
  await page.getByRole('button', { name: '保存支付配置' }).click();
  assert.equal((await settingsSaved).status(), 200);
  assert.equal((await call('/api/admin/settings')).data.exchangeRate, '7.3500');
  await call('/api/admin/settings', 'PATCH', originalSettings);
  assert.equal((await call('/api/admin/settings', 'PATCH', { ...originalSettings, usdtEnabled: true, walletAddress: 'invalid' })).status, 400);
  log('Payment configuration persistence and invalid receiver rejection');
  const usdtCallback = await call('/api/payments/usdt/confirm', 'POST', {});
  assert.ok([401, 501].includes(usdtCallback.status));
  assert.equal((await context.request.post(`${base}/api/payments/alipay/notify`, { form: { trade_status: 'TRADE_SUCCESS' } })).status(), 503);
  log('Unsigned or unconfigured callbacks cannot change payment state');
  await page.goto(`${base}/admin`);
  await page.locator('.stat-card').first().waitFor();
  const stats = (await call('/api/admin/overview')).data;
  assert.equal(stats.revenue, 139);
  assert.equal(stats.completed, 1);
  await page.screenshot({ path: 'artifacts/admin-overview.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.getByRole('button', { name: '打开管理菜单' }).click();
  await page.locator('.admin-nav').getByRole('link', { name: '订单管理' }).click();
  await page.locator('.data-table').waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.screenshot({ path: 'artifacts/admin-mobile.png', fullPage: true });
  log('Real aggregated statistics and responsive admin navigation');
  await page.getByRole('button', { name: '打开管理菜单' }).click();
  await page.getByRole('button', { name: '退出登录', exact: true }).click();
  await page.waitForURL(`${base}/admin-login`);
  assert.equal((await call('/api/admin/orders')).status, 401);
  assert.deepEqual(browserErrors, []);
  log('Logout invalidates session; no uncaught browser exceptions');
  console.log('ALL ACCEPTANCE TESTS PASSED');
} finally {
  await browser.close();
  if (fixtureIds.length) await db.delete(orders).where(inArray(orders.id, fixtureIds));
  if (fixturePlanId) await db.delete(plans).where(eq(plans.id, fixturePlanId));
  if (originalSettings) await db.update(paymentSettings).set(originalSettings).where(eq(paymentSettings.id, 1));
  await db.delete(admins).where(eq(admins.username, username));
  await pool.end();
  console.log('Temporary orders, package, administrator and configuration changes cleaned up.');
}
